### ISSUE TITLE
Adding 7zip as a program to download

### ISSUE THREAD

**Issue by ih8ih8sn0w** [Plailect/Guide_3DS#1487]
Essentially, people are either running into an issue where the don't know how to extract luma (or anything else which may use 7 zips) or they are using WinRAR which potentially corrupts the firm when extracting (only have reports from sonlen and some others on this, nothing really confirmed). As I mentioned on Discord, it would be best to explain this near the same block as the torrent client.

**Comment by ihaveamac** [comment]
for macOS: https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12 (non-MAS link: https://theunarchiver.com)
