### ISSUE TITLE
Install B9S Using Seedminer

### ISSUE THREAD

**Issue by SassyCultist** [Plailect/Guide_3DS#1491]
This is a valid method for installing B9S on a user's 3ds that I think should be included in the guide. It allows for single system dsiware injection.

Gbatemp:
https://gbatemp.net/threads/seedminer-single-system-dsiware-injection.495685/

Github:
https://github.com/zoogie/seedminer

**Comment by safan41** [comment]
I think you should simply link to jisagi's guide (https://jisagi.github.io/SeedminerGuide/) instead of completely remaking a guide.

**Comment by Plailect** [comment]
Added link, but the page needs editing to address the addition.
