### ISSUE TITLE
Advertisement in an odd place

### ISSUE THREAD

**Issue by SirNapkin1334** [Plailect/Guide_3DS#1519]
Hey, while I was browsing through the guide (actually so I could find a place where a specific element was stored for a future PR), I noticed an Advertisement in a very odd place.

![image](https://user-images.githubusercontent.com/31591796/38168670-6490c456-3508-11e8-9ae7-057e780d159a.png)

As far as I can tell, Advertisements are not supposed to appear *in* Markdown colored-boxes. Is it supposed to happen?

**Comment by Plailect** [comment]
That's...weird. I bet google is doing some more A/B testing I didn't ask for :/

**Comment by Plailect** [comment]
think I got this fixed
