### ISSUE TITLE
Incorporate pre9otherapp in the list of O3DS methods

### ISSUE THREAD

**Issue by jason0597** [Plailect/Guide_3DS#1525]
@Pirater12 released [pre9otherapp](https://github.com/Pirater12/otherapp), which allows O3DS users to run Soundhax on pre 9.X firmwares (down to 4.X since that's the last version where firmlaunch-hax works). 
It basically makes it so that you only need the soundhax `.m4a` file, the pre9otherapp, and an `arm9.bin` payload (e.g. SafeB9SInstaller).

Perhaps it could be added to the list of possible methods for O3DS? This would be useful for people without a web browser.

**Comment by Pirater12** [comment]
It works on n3ds too.

**Comment by Plailect** [comment]
I have been keeping an eye on this since its release, though I am waiting for more testing and the existing bugs (with 4.X and 8.1.0-0J) to be fixed before incorporating it into the guide. Once that happens, quite a few things can be simplified.

**Comment by Pirater12** [comment]
@Plailect I have added support for 8.1.0-0J confirmed to be working by @ihaveamac, but as in for 4.X, I'm not getting time to debug soundhax. So yeah, it can used with soundhax for 8.1.0-0J.

**Comment by Plailect** [comment]
Okay, I will look into adding it for versions other than 4.X soon.

**Comment by Pirater12** [comment]
I and @saibotu were able to get soundhax to work on 4.X and tested pre9otherapp, it works.
