### ISSUE TITLE
The 9.0.0 - 11.3.0 guide is actually only for 11.3.0

### ISSUE THREAD

**Issue by Filo97** [Plailect/Guide_3DS#1533]
UDSploit only works on 11.3.0. I was hacking my cousins's 3ds when i realized. It was on 11.2, so UDSploit wasn't working at all. I had to use fasthax. Might want to fix that.

**Comment by Filo97** [comment]
Yes, i had it on. And no i didn't get any of the errors mentioned by the guide. It was stuck on figuring out the avaiable memory, while fasthax worked in 2 seconds first try.

**Comment by Plailect** [comment]
Not sure why you had issues, it 100% works for sure.
