### ISSUE TITLE
Why not use the DS ntrboot flasher v5.x for single system ntrboot?

### ISSUE THREAD

**Issue by zacchi4k** [Plailect/Guide_3DS#1537]
[Ntrboot flasher 5.0/5.1](https://github.com/jason0597/ntrboot_flasher_nds/releases/) is compatible with more cards (like the Ace3DS+, which is even listed in [this picture](https://3ds.hacks.guide/images/screenshots/ntrboot-flashcarts.png) found on the website), allows backing up the flashcart's firmware to later restore it even if no dumps have been released to the Internet, and even allows flashing any FIRM you want (which doesn't really matter that much for the guide's scope, but it would allow flashing newer B9S versions, if released), and it also has a much nicer interface with resembles the 3DS ntrboot flasher. It's overall a much superior flasher compared to the old flasher, and I don't see why the guide couldn't use it.

**Comment by Plailect** [comment]
I had been considering a move to this for a while, though I was under the impression this would eventually be the official DS flasher under the ntrteam group (though that was last discussed a while ago so I'm not sure if that's still planned).

**Comment by zacchi4k** [comment]
I contacted jason0597, here's what he said:
"the old one is made by someone else (who has disappeared into god knows where)
the new one is a rewrite by me and a few others, and it's 100% independent from it, its code is written completely from scratch
i can't merge it because it's not a few patches, it's a complete rewrite 

as for getting it to be official, Kitilith (one of the heads of flashcart_core) has contacted me about it and it will happen someday"

**Comment by zacchi4k** [comment]
Since only the new one will be updated, and the old one will become progressively more outdated, I don't see any reason to not update the guide

**Comment by Plailect** [comment]
I spoke with the author and they require further testing before they are comfortable with it being used.

**Comment by zacchi4k** [comment]
Just a quick word on this... apparently the ntrboot project [has been discontinued](https://github.com/ntrteam/ntrboot_flasher/commit/61318453612139c5964b4ad3fb3f2b82fef875d2).  Now, while the new flasher hasn't been tested thoroughly tested as the old one, I used it multiple times on my card with no problems, and other people on GBAtemp have had success with it when the old one doesn't work.

**Comment by zacchi4k** [comment]
A small mistake I noticed, what's stated [here](https://github.com/Plailect/Guide_3DS/commit/df8a34914bb3e85cde4b92700d8545fba217b287#diff-53bdd1472bc4d9c79d9d560cbb6b0dbbR94) is wrong because the flashrom is saved on the flashcart's microSD, not on the console SD card, so it needs to be copied to the console SD card first

**Comment by Plailect** [comment]
Fixed ^

**Comment by zacchi4k** [comment]
And another small thing, the filename for the flasher changed into `ntrboot_flasher_nds.nds`, but both the 3DS and NDS pages still report the old filename

**Comment by Plailect** [comment]
Fixed ^
