### ISSUE TITLE
R4i Gold 3DS HW version D Flash backup

### ISSUE THREAD

**Issue by StevenSeegal** [Plailect/Guide_3DS#1541]
I have an R4i Gold 3DS HW version D (probably a clone). Flashed it with Ntrboot and works like a charm. I've kept the original flash backup and since that version is not listed on de 3dshacks site I just wanted to know if you fancy it me sharing it so you can add it. I've put the bin and a photo of the card (so you can see the HW version) inside the zip.

[Zip on filetrip](https://filetrip.net/dl?19d3PFWDND)

**Comment by Plailect** [comment]
thanks!
