### ISSUE TITLE
DSiWare save injection not working on 11.8 with Zelda

### ISSUE THREAD

**Issue by 040044** [Plailect/Guide_3DS#1566]
Hi,
I was following the guide and did everything correctly, but when I get to the part where I'm supposed to launch b9sTool through the zelda game, I'm getting a white screen.
You said [here](https://github.com/Plailect/b9sTool/releases/tag/v2.1.0) that "This binary has been replaced with one compiled with old libnds. Binaries compiled with new libnds will fail to boot when launched by 4swordshax (just shows a white screen)."
Is it possible to have the latest version of b9sTool for the 11.8 firmware and that works with Zelda Four Swords? Because right now, people will follow the guide just like I did and get stuck without any other information.
Thanks.

**Comment by Plailect** [comment]
There's an updated version of 4swordshax that can use the new libnds, I'll switch to using that.
