### ISSUE TITLE
"Missing" stuff from A9LH to B9S page

### ISSUE THREAD

**Issue by zacchi4k** [Plailect/Guide_3DS#1576]
After following the A9LH to B9S page myself, I found some stuff that could be added to the guide:

- ~~In the Cleanup SD Card script, there are a few other files that could be deleted, namely Menuhax files (payload and installer) (along with other obsolete *hax stuff), SafeB9SInstaller.bin from the Luma payloads folder and arm9loaderhax.bin in the CTRNAND, H&S injection files and also maybe the a9lh folder and older stuff like Hourglass9 too?~~ Just realized this is could be more of a Gm9 issue
- In [Section VI](https://3ds.hacks.guide/a9lh-to-b9s#section-vi---homebrew-launcher), the first step says to launch the Homebrew Launcher application, but then the last one says to close the Download Play application. Personally, I think the Download Play+Rosalina route (the one in the OFW to CFW guide) would be better between the two.
- Someone upgrading from A9LH to B9S is bound to have outdated versions of homebrew applications installed, so maybe this page should also instruct on updating them to the latest version (maybe providing the steps to update FBI and hblauncher_loader, which are the most important, and then telling the user that they should check for updates for the homebrew applications installed and update them if needed)
- A guide for restoring the H&S application in case it has been injected with FBI should be added. I think the best method would be going into FBI, deleting the FBI SysNAND title and perform a system update, since it can be done even if the backup files were deleted/lost
- Most of the "footnotes" from the OFW to CFW guide are missing in this page (eg: NTR CFW, info about Luma3DS and GM9, moving to a bigger SD and others)

**Comment by zacchi4k** [comment]
As a prime example, I got the A9LH 3DS from a friend, and he never restored the original application and he removed the files on the SD, so I had to delete the application and do a system update

**Comment by Plailect** [comment]
Ah, well in that case it should really be a separate troubleshooting section or something as that's atypical of the normal case.

**Comment by zacchi4k** [comment]
You mean maybe another footnote linking to a separate section in the troubleshooting page?

**Comment by Plailect** [comment]
Not necessarily a footnote, but something like that.

**Comment by Plailect** [comment]
Since it's not a huge deal, I'll add that at a later time and push fixes now for everything else.

**Comment by zacchi4k** [comment]
What about the Gm9 script? Will you take care of that or should I open an issue/pull request on Gm9's repo?

**Comment by Plailect** [comment]
The latter.
