### ISSUE TITLE
Unseeded torrents

### ISSUE THREAD

**Issue by iuzwpr2p39rh7w** [Plailect/Guide_3DS#1580]
A [commit](https://github.com/Plailect/Guide_3DS/commit/679bc5192820cb11c5d2a6a9243d82b89a33a519#diff-2482af372b704269e635be1cd55226edR4658) from more than a week ago added four new torrents and modified two existing ones. The latter either have not been seeded yet, or I misconfigured my torrent client.

Sedded:
`ctcert.bin` (EC445A7AAE6FD62432C9CCEE091919BDA41C8283)
`EUR.zip` (FE5BE30F2A2C33E5E350E099804840560CBB6626)
`JPN.zip` (B10E9C3289C16C6DE8AEFCAF3892E2EFE267ACB8)
`USA.zip` (EAD76F1E382CAD15EFAF1BA87C702F7B4C16D6E0)

Unseeded:
`DSiWare_eur_sudokuhax_injection.zip` (1542DD3C2BF7785B1E7A6DDA3887FC8FB2710685 -> 635C79AC8CEE2AECEE7B45AC69E0AC54108E21AB)
`DSiWare_usa_sudokuhax_injection.zip` (7ED7FEE15C900ED02B5E2CB3C8E7A0363F4D9354 -> 122CD5DDF913A3615E1B49CD25B9F59D4CD1B275)

**Comment by Plailect** [comment]
Odd, give me a minute and I'll try and fix that.

**Comment by Plailect** [comment]
Try again now?

**Comment by iuzwpr2p39rh7w** [comment]
The USA one works, but the EUR one does not want to download.

**Comment by iuzwpr2p39rh7w** [comment]
I'm in Europe.

**Comment by Plailect** [comment]
Well I'll make sure that seeding continues. Just leave the client open and hopefully you will eventually get a connection.
