### ISSUE TITLE
Add the "r4iiisdhc.com" in the list of compatible ntrboot cards

### ISSUE THREAD

**Issue by zacchi4k** [Plailect/Guide_3DS#1582]
According to [this](https://gbatemp.net/threads/configuring-this-flashcard-to-mod-3ds.515746/), the "R4 Upgrade Revolution for Nintendo DS" from "r4iiisdhc.com" can be used for ntrboot by selecting the DSTT option. It doesn't appear to be recognized by a 3DS (so I assume it's not recognized on DSi either?), which means a DS/DSL must be used, and there's a picture of the cart in the OP

**Comment by Plailect** [comment]
It would be impractical for me to list every single flashcart clone that happens to work (nor can I guarantee anything works outside of the carts listed in the flashcart_core readme).
