### ISSUE TITLE
An issue and a suggestion related to notices

### ISSUE THREAD

**Issue by Mike15678** [Plailect/Guide_3DS#1583]
Let’s start off with the issue: https://github.com/Plailect/Guide_3DS/blob/master/_pages/en_US/installing-boot9strap-(seedminer).txt doesn’t have a torrent client notice and a .7z archive notice.
Now onto the suggestion: The two notices I just described would probably be better off being embedded into orange info boxes in order to lessen the amount of people who would skip over them. This would have to be changed on multiple pages though in order to be beneficial.

**Comment by Plailect** [comment]
An overload of notice boxes was an issue in the past and I receive a lot of feedback indicating that those aren't considered important enough to merit their own notice box.
