### ISSUE TITLE
Error es_ES

### ISSUE THREAD

**Issue by yonaikerlol** [Plailect/Guide_3DS#1592]
Google Translate version:

In the version es_ES/godmode9-usage#convert-a-file-3ds-a-cia, there is a link that redirects to #dumping-a-game-cartridge, and it should be #volcar-un-cartucho-de-juego...

**Comment by Plailect** [comment]
Translation project issues should be directed to [Crowdin](https://crowdin.com/project/3ds-guide).

**Comment by jkcgs** [comment]
The issue is now fixed and will be up with the next translations update. You can see the string in question [here](https://crowdin.com/translate/3ds-guide/216/en-es#22796). You can also contribute with translations there!

(also, sorry for answering here, @Plailect)
