### ISSUE TITLE
Following "Updating B9S" guide leads to irrelevant files being copied to NAND

### ISSUE THREAD

**Issue by mariomadproductions** [Plailect/Guide_3DS#1593]
When “Setup Luma3DS to CTRNAND” is ran, the whole "luma" folder on the sd card seems to be copied to the "luma" folder on CTRNAND.

**Comment by Plailect** [comment]
These files are not really "irrelevant". You likely would want all your other luma configuration/mods/files/etc...

**Comment by mariomadproductions** [comment]
I don't think its really practical to use mods from the NAND - the files can be large and the user may want to change the files (if testing a mod or adding more mods). The user should be able to choose.

**Comment by Plailect** [comment]
Let's move this discussion here: https://github.com/d0k3/GodMode9/issues/427
