### ISSUE TITLE
Suggestion: state what scripts do

### ISSUE THREAD

**Issue by mariomadproductions** [Plailect/Guide_3DS#1594]
Scripts can delete files that users want to keep, and the user may want to know exactly what the script is doing/do it themselves. So rather than leaving the user to open the script up in a text editor and work it out from that, the guide should simply list what the script does.

**Comment by Plailect** [comment]
I don't really feel like this is necessary. Users don't always need to know the specifics of what a program/script is doing in the background as long as it works, and those who care about all of the specific details can just read it as you have pointed out is possible.
