### ISSUE TITLE
stuck on Arm11.bin loading

### ISSUE THREAD

**Issue by SoporMuse** [Plailect/Guide_3DS#1597]
So I went through another thread that was troubleshooting this error, but I couldn't find any solutions, and I noticed it was a dated thread, so I'm hoping something new might solve this. I'm going through the guide and I can't seem to get past the browser portion where it tells me to go to http://2xrsa.hacks.guide. After typing in that URL, the screen prompts me to a page that only says "arm11.bin loading". I noticed that this particular error isn't in the troubleshooting options, so I'm hoping there are some means of troubleshooting that could help with this. Things I've troubleshot thus far:

-Verified the SD card through h2testw
-redid the steps leading up to the URL directions.

Let me know if there's anything I can provide that would assist anyone, thanks in advance!

**Comment by zacchi4k** [comment]
the 2xrsa method only works on 2.1.0. Any other version won't work

**Comment by SoporMuse** [comment]
Oh I gotcha, thank you! Which alternative should I be using? 3ds version is saying "11.8.0-41U"
