### ISSUE TITLE
Missing renaming step to launch SafeB9SInstaller

### ISSUE THREAD

**Issue by nanashi6014** [Plailect/Guide_3DS#1601]
On the "A9LH to B9S" page, following the steps won't launch SafeB9SInstaller in Section II, Step 1.

A step needs to be added in Section I, between current steps 19 and 20, to rename _SafeB9SInstaller.bin_ to _start_SafeB9SInstaller.bin_

**Comment by Plailect** [comment]
This is unnecessary as holding start will cause the chainloader menu to appear, allowing you to select SafeB9SInstaller.
